In [48]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [49]:
from warnings import filterwarnings
filterwarnings('ignore')

In [50]:
from sklearn import datasets as data
boston = data.load_boston()
df = pd.DataFrame(boston.data,columns=boston.feature_names)
df['value'] = boston.target
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  value  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

In [51]:
print(boston.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [52]:
from sklearn.linear_model import LinearRegression
X = boston.data
y = boston.target
lr = LinearRegression()
lr.fit(X,y)

LinearRegression()

In [53]:
lr.coef_

array([-1.08011358e-01,  4.64204584e-02,  2.05586264e-02,  2.68673382e+00,
       -1.77666112e+01,  3.80986521e+00,  6.92224640e-04, -1.47556685e+00,
        3.06049479e-01, -1.23345939e-02, -9.52747232e-01,  9.31168327e-03,
       -5.24758378e-01])

In [54]:
lr.intercept_

36.45948838509002

In [55]:
yhat = lr.predict(X)

In [56]:
from sklearn.metrics import r2_score, mean_squared_error
print(r2_score(y,yhat))
print(mean_squared_error(y,yhat))

0.7406426641094094
21.894831181729206


# Using Statsmodels

In [57]:
import statsmodels.api as sm
model = sm.OLS(y,X)    #(y,X) instead of (X,y)
result = model.fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.959
Model:                            OLS   Adj. R-squared (uncentered):              0.958
Method:                 Least Squares   F-statistic:                              891.3
Date:                Fri, 14 Oct 2022   Prob (F-statistic):                        0.00
Time:                        13:50:33   Log-Likelihood:                         -1523.8
No. Observations:                 506   AIC:                                      3074.
Df Residuals:                     493   BIC:                                      3128.
Df Model:                          13                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -0.0929      0.034     -2.699      0.007      -0.161      -0.025
x2             0.0487      0.014      3.382      0.001       0.020       0.077
x3            -0.0041      0.064     -0.063      0.950      -0.131       0.123
x4             2.8540      0.904      3.157      0.002       1.078       4.630
x5            -2.8684      3.359     -0.854      0.394      -9.468       3.731
x6             5.9281      0.309     19.178      0.000       5.321       6.535
x7            -0.0073      0.014     -0.526      0.599      -0.034       0.020
x8            -0.9685      0.196     -4.951      0.000      -1.353      -0.584
x9             0.1712      0.067      2.564      0.011       0.040       0.302
x10           -0.0094      0.004     -2.395      0.017      -0.017      -0.002
x11           -0.3922      0.110     -3.570      0.000      -0.608      -0.176
x12            0.0149      0.003      5.528      0.000       0.010       0.020
x13           -0.4163      0.051     -8.197      0.000      -0.516      -0.317
==============================================================================
Omnibus:                      204.082   Durbin-Watson:                   0.999
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1374.225
Skew:                           1.609   Prob(JB):                    3.90e-299
Kurtosis:                      10.404   Cond. No.                     8.50e+03
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 8.5e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [58]:
#We forgot to add the constant.
#Now we will add constant
import statsmodels.api as sm
X_train = sm.add_constant(X)
model = sm.OLS(y,X_train)
result = model.fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.741
Model:                            OLS   Adj. R-squared:                  0.734
Method:                 Least Squares   F-statistic:                     108.1
Date:                Fri, 14 Oct 2022   Prob (F-statistic):          6.72e-135
Time:                        13:50:33   Log-Likelihood:                -1498.8
No. Observations:                 506   AIC:                             3026.
Df Residuals:                     492   BIC:                             3085.
Df Model:                          13                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         36.4595      5.103      7.144      0.000      26.432      46.487
x1            -0.1080      0.033     -3.287      0.001      -0.173      -0.043
x2             0.0464      0.014      3.382      0.001       0.019       0.073
x3             0.0206      0.061      0.334      0.738      -0.100       0.141
x4             2.6867      0.862      3.118      0.002       0.994       4.380
x5           -17.7666      3.820     -4.651      0.000     -25.272     -10.262
x6             3.8099      0.418      9.116      0.000       2.989       4.631
x7             0.0007      0.013      0.052      0.958      -0.025       0.027
x8            -1.4756      0.199     -7.398      0.000      -1.867      -1.084
x9             0.3060      0.066      4.613      0.000       0.176       0.436
x10           -0.0123      0.004     -3.280      0.001      -0.020      -0.005
x11           -0.9527      0.131     -7.283      0.000      -1.210      -0.696
x12            0.0093      0.003      3.467      0.001       0.004       0.015
x13           -0.5248      0.051    -10.347      0.000      -0.624      -0.425
==============================================================================
Omnibus:                      178.041   Durbin-Watson:                   1.078
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              783.126
Skew:                           1.521   Prob(JB):                    8.84e-171
Kurtosis:                       8.281   Cond. No.                     1.51e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.51e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

# Check for VIF for multicollinearity

In [59]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif = pd.DataFrame()
collist = boston.feature_names
print(collist)

['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


In [60]:
vif['features'] = collist

In [61]:
X = df[collist].values
y = df['value'].values
print(X)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [62]:
X.shape[1]

13

In [63]:
vif['VIF'] = [variance_inflation_factor(X,i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'],2)
vif = vif.sort_values(by="VIF",ascending = False)
vif

features    VIF
10  PTRATIO  85.03
5        RM  77.95
4       NOX  73.89
9       TAX  61.23
6       AGE  21.39
11        B  20.10
8       RAD  15.17
7       DIS  14.70
2     INDUS  14.49
12    LSTAT  11.10
1        ZN   2.84
0      CRIM   2.10
3      CHAS   1.15

In [65]:
print(collist)

['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


# Model 1

In [66]:
#Removing PTRATIO
collist1 = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',  'B', 'LSTAT']
X = df[collist1].values
y = df['value'].values

In [67]:
import statsmodels.api as sm
X_C= sm.add_constant(X)
model1 = sm.OLS(y, X_C)
result = model1.fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.713
Model:                            OLS   Adj. R-squared:                  0.706
Method:                 Least Squares   F-statistic:                     101.9
Date:                Fri, 14 Oct 2022   Prob (F-statistic):          4.56e-125
Time:                        13:52:24   Log-Likelihood:                -1524.7
No. Observations:                 506   AIC:                             3075.
Df Residuals:                     493   BIC:                             3130.
Df Model:                          12                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         14.1689      4.294      3.300      0.001       5.732      22.605
x1            -0.1030      0.035     -2.981      0.003      -0.171      -0.035
x2             0.0775      0.014      5.652      0.000       0.051       0.104
x3            -0.0376      0.064     -0.587      0.558      -0.164       0.088
x4             3.2744      0.902      3.630      0.000       1.502       5.047
x5            -8.5977      3.792     -2.267      0.024     -16.048      -1.148
x6             4.2952      0.434      9.901      0.000       3.443       5.148
x7            -0.0068      0.014     -0.493      0.622      -0.034       0.020
x8            -1.6115      0.209     -7.718      0.000      -2.022      -1.201
x9             0.2148      0.069      3.135      0.002       0.080       0.349
x10           -0.0144      0.004     -3.653      0.000      -0.022      -0.007
x11            0.0087      0.003      3.067      0.002       0.003       0.014
x12           -0.5415      0.053    -10.166      0.000      -0.646      -0.437
==============================================================================
Omnibus:                      161.318   Durbin-Watson:                   0.983
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              622.859
Skew:                           1.411   Prob(JB):                    5.59e-136
Kurtosis:                       7.645   Cond. No.                     1.24e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.24e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [68]:
# Create a dataframe that will contain the names of all the feature variables and their respective VIFs
vif1 = pd.DataFrame()
vif1['features'] = collist1
vif1['VIF'] = [variance_inflation_factor(X, i) for i in range(X.shape[1])]

In [69]:
vif1['VIF'] = round(vif1['VIF'], 2)
vif1 = vif1.sort_values(by = "VIF", ascending = False)
vif1

features    VIF
4       NOX  73.89
5        RM  60.60
9       TAX  59.30
6       AGE  21.36
10        B  18.61
8       RAD  15.16
2     INDUS  14.28
7       DIS  12.22
11    LSTAT  10.14
1        ZN   2.45
0      CRIM   2.10
3      CHAS   1.14

In [71]:
#Similarly we go till model 4
collist4 =  ['CRIM', 'ZN', 'CHAS', 'DIS', 'LSTAT' ]
X = df[collist4].values
y = df['value'].values
import statsmodels.api as sm
X_C= sm.add_constant(X)
model1 = sm.OLS(y, X_C)
result = model1.fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.615
Model:                            OLS   Adj. R-squared:                  0.611
Method:                 Least Squares   F-statistic:                     159.8
Date:                Fri, 14 Oct 2022   Prob (F-statistic):          3.25e-101
Time:                        13:55:14   Log-Likelihood:                -1598.7
No. Observations:                 506   AIC:                             3209.
Df Residuals:                     500   BIC:                             3235.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         38.6749      0.982     39.382      0.000      36.745      40.604
x1            -0.1260      0.034     -3.668      0.000      -0.194      -0.059
x2             0.0970      0.015      6.520      0.000       0.068       0.126
x3             3.9447      1.020      3.869      0.000       1.942       5.948
x4            -1.3574      0.178     -7.617      0.000      -1.708      -1.007
x5            -0.9414      0.044    -21.193      0.000      -1.029      -0.854
==============================================================================
Omnibus:                      114.340   Durbin-Watson:                   1.087
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              223.265
Skew:                           1.252   Prob(JB):                     3.30e-49
Kurtosis:                       5.078   Cond. No.                         115.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [76]:
# Model 5
collist5 = ['RM','CHAS','LSTAT']
X = df[collist5].values
y = df['value'].values
import statsmodels.api as sm
X_C= sm.add_constant(X)
model1 = sm.OLS(y, X_C)
result = model1.fit()
result.summary()


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.651
Model:                            OLS   Adj. R-squared:                  0.649
Method:                 Least Squares   F-statistic:                     312.7
Date:                Fri, 14 Oct 2022   Prob (F-statistic):          1.92e-114
Time:                        14:04:18   Log-Likelihood:                -1573.6
No. Observations:                 506   AIC:                             3155.
Df Residuals:                     502   BIC:                             3172.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.7637      3.122     -0.245      0.807      -6.898       5.370
x1             4.9558      0.438     11.311      0.000       4.095       5.817
x2             4.1205      0.958      4.300      0.000       2.238       6.003
x3            -0.6428      0.043    -14.953      0.000      -0.727      -0.558
==============================================================================
Omnibus:                      133.400   Durbin-Watson:                   0.930
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              414.658
Skew:                           1.229   Prob(JB):                     9.08e-91
Kurtosis:                       6.691   Cond. No.                         202.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [77]:
# Create a dataframe that will contain the names of all the feature variables and their respective VIFs
vif5 = pd.DataFrame()
vif5['features'] = collist5
X = df[collist5].values
y = df['value'].values
vif5['VIF'] = [variance_inflation_factor(X, i) for i in range(X.shape[1])]
vif5['VIF'] = round(vif5['VIF'], 2)
vif5 = vif5.sort_values(by = "VIF", ascending = False)
vif5

features   VIF
0       RM  3.37
2    LSTAT  3.26
1     CHAS  1.08

# Now trying Recursive Feature Elimination and building model

In [89]:
from sklearn.feature_selection import RFE
X = boston.data
y = boston.target
lr = LinearRegression()
rfe = RFE(lr,step=1,verbose=1)
x_red = rfe.fit_transform(X,y)

lr.fit(x_red,y)
print(lr.coef_)
print(lr.intercept_)
yhat = lr.predict(x_red)
from sklearn.metrics import r2_score,mean_squared_error
print(r2_score(y,yhat))
print(mean_squared_error(y,yhat))
print(lr.score(x_red,y))

Fitting estimator with 13 features.
Fitting estimator with 12 features.
Fitting estimator with 11 features.
Fitting estimator with 10 features.
Fitting estimator with 9 features.
Fitting estimator with 8 features.
Fitting estimator with 7 features.
[  3.24430477 -18.74043265   4.11181168  -1.14458566  -1.00274627
  -0.56984422]
36.922634038052934
0.7157742117396082
23.99421489307857
0.7157742117396082


In [90]:
columns[rfe.get_support()]

Index(['CHAS', 'NOX', 'RM', 'DIS', 'PTRATIO', 'LSTAT'], dtype='object')

In [87]:
columns = df.drop(['value'], axis=1).columns
columns[rfe.get_support()]
rfe = RFE(lr, n_features_to_select=3, step=1, verbose=1)
x_red = rfe.fit_transform(X, y)

lr.fit(x_red, y)
print(lr.score(x_red, y))

Fitting estimator with 13 features.
Fitting estimator with 12 features.
Fitting estimator with 11 features.
Fitting estimator with 10 features.
Fitting estimator with 9 features.
Fitting estimator with 8 features.
Fitting estimator with 7 features.
Fitting estimator with 6 features.
Fitting estimator with 5 features.
Fitting estimator with 4 features.
0.5555737130590868


In [85]:
columns[rfe.get_support()]

Index(['CHAS', 'NOX', 'RM'], dtype='object')

In [88]:
#The End